[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aquamarine-nexus"
version = "1.0.0"
authors = [
  { name="Soma Dutta" }
]
description = "Sovereign Zero-Dependency Pure Scientific CAS, Quantum Biophysics, 4D Spacetime Geodesic & JIT Kernel"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
]

[project.scripts]
aquamarine-nexus = "aquamarine_nexus.cli:main"
aqua = "aquamarine_nexus.core.aqua_shell_editor:main"
